name: expense_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.2
  intl: ^0.17.0
  pie_chart: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/img/Exp.png"
  

flutter:
  uses-material-design: true
